In [30]:
import os
import pandas as pd
import numpy as np
import plotly.express as px
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# CS:GO Round Winner Classification


URL: https://www.kaggle.com/christianlillelund/csgo-round-winner-classification

In [31]:
df_cs = pd.read_csv(os.path.join('dataset', 'csgo_round_snapshots.csv'))
df_cs.shape

(122410, 97)

In [32]:
df_cs.head()

time_left  ct_score  t_score       map  bomb_planted  ct_health  t_health  \
0     175.00       0.0      0.0  de_dust2         False      500.0     500.0   
1     156.03       0.0      0.0  de_dust2         False      500.0     500.0   
2      96.03       0.0      0.0  de_dust2         False      391.0     400.0   
3      76.03       0.0      0.0  de_dust2         False      391.0     400.0   
4     174.97       1.0      0.0  de_dust2         False      500.0     500.0   

   ct_armor  t_armor  ct_money  ...  t_grenade_flashbang  \
0       0.0      0.0    4000.0  ...                  0.0   
1     400.0    300.0     600.0  ...                  0.0   
2     294.0    200.0     750.0  ...                  0.0   
3     294.0    200.0     750.0  ...                  0.0   
4     192.0      0.0   18350.0  ...                  0.0   

   ct_grenade_smokegrenade  t_grenade_smokegrenade  \
0                      0.0                     0.0   
1                      0.0                     2.0   
2                      0.0                     2.0   
3                      0.0                     0.0   
4                      0.0                     0.0   

   ct_grenade_incendiarygrenade  t_grenade_incendiarygrenade  \
0                           0.0                          0.0   
1                           0.0                          0.0   
2                           0.0                          0.0   
3                           0.0                          0.0   
4                           0.0                          0.0   

   ct_grenade_molotovgrenade  t_grenade_molotovgrenade  \
0                        0.0                       0.0   
1                        0.0                       0.0   
2                        0.0                       0.0   
3                        0.0                       0.0   
4                        0.0                       0.0   

   ct_grenade_decoygrenade  t_grenade_decoygrenade  round_winner  
0                      0.0                     0.0            CT  
1                      0.0                     0.0            CT  
2                      0.0                     0.0            CT  
3                      0.0                     0.0            CT  
4                      0.0                     0.0            CT  

[5 rows x 97 columns]

In [33]:
df_cs.describe()

time_left       ct_score        t_score      ct_health  \
count  122410.000000  122410.000000  122410.000000  122410.000000   
mean       97.886922       6.709239       6.780435     412.106568   
std        54.465238       4.790362       4.823543     132.293290   
min         0.010000       0.000000       0.000000       0.000000   
25%        54.920000       3.000000       3.000000     350.000000   
50%        94.910000       6.000000       6.000000     500.000000   
75%       166.917500      10.000000      10.000000     500.000000   
max       175.000000      32.000000      33.000000     500.000000   

            t_health       ct_armor        t_armor       ct_money  \
count  122410.000000  122410.000000  122410.000000  122410.000000   
mean      402.714500     314.142121     298.444670    9789.023773   
std       139.919033     171.029736     174.576545   11215.042286   
min         0.000000       0.000000       0.000000       0.000000   
25%       322.000000     194.000000     174.000000    1300.000000   
50%       500.000000     377.000000     334.000000    5500.000000   
75%       500.000000     486.000000     468.000000   14600.000000   
max       600.000000     500.000000     500.000000   80000.000000   

             t_money     ct_helmets  ...  ct_grenade_flashbang  \
count  122410.000000  122410.000000  ...         122410.000000   
mean    11241.036680       2.053901  ...              1.853157   
std     12162.806759       1.841470  ...              1.772791   
min         0.000000       0.000000  ...              0.000000   
25%      1550.000000       0.000000  ...              0.000000   
50%      7150.000000       2.000000  ...              1.000000   
75%     18000.000000       4.000000  ...              3.000000   
max     80000.000000       5.000000  ...              7.000000   

       t_grenade_flashbang  ct_grenade_smokegrenade  t_grenade_smokegrenade  \
count        122410.000000            122410.000000           122410.000000   
mean              1.858100                 1.540814                1.627146   
std               1.794473                 1.737804                1.829147   
min               0.000000                 0.000000                0.000000   
25%               0.000000                 0.000000                0.000000   
50%               1.000000                 1.000000                1.000000   
75%               3.000000                 3.000000                3.000000   
max               7.000000                 6.000000                9.000000   

       ct_grenade_incendiarygrenade  t_grenade_incendiarygrenade  \
count                 122410.000000                122410.000000   
mean                       1.001969                     0.019819   
std                        1.458084                     0.143933   
min                        0.000000                     0.000000   
25%                        0.000000                     0.000000   
50%                        0.000000                     0.000000   
75%                        2.000000                     0.000000   
max                        5.000000                     3.000000   

       ct_grenade_molotovgrenade  t_grenade_molotovgrenade  \
count              122410.000000             122410.000000   
mean                    0.048011                  1.352095   
std                     0.227669                  1.663246   
min                     0.000000                  0.000000   
25%                     0.000000                  0.000000   
50%                     0.000000                  1.000000   
75%                     0.000000                  2.000000   
max                     3.000000                  5.000000   

       ct_grenade_decoygrenade  t_grenade_decoygrenade  
count            122410.000000           122410.000000  
mean                  0.027694                0.025750  
std                   0.169531                0.164162  
min                   0.000000                0.000000  
25%

In [34]:
df_cs.replace('CT', 1, inplace=True)
df_cs.replace('T', 0, inplace=True)
df_cs['bomb_planted'] = df_cs['bomb_planted'].astype(int)

In [35]:
# default 0.25 test
train, test = train_test_split(df_cs, train_size=0.2)

# p = 1

In [7]:
train_input_var = train['time_left'].values.reshape(-1, 1)
train_input_target = train['round_winner'].astype(int)

test_input_var = test['time_left'].values.reshape(-1, 1)
test_input_target = test['round_winner'].astype(int)

scaler = StandardScaler()
train_input_var = scaler.fit_transform(train_input_var)
test_input_var = scaler.transform(test_input_var)

In [8]:
model = LogisticRegression()
model = model.fit(train_input_var, train_input_target)

In [20]:
train.columns[np.argmax(model.coef_)]

'bomb_planted'

## Train eval

In [9]:
model.score(train_input_var, train_input_target)

0.5206792510375026

In [10]:
confusion_matrix(train_input_target, model.predict(train_input_var).astype(float))

array([[29827, 16941],
       [27064, 17975]])

## Test eval

In [11]:
model.score(test_input_var, test_input_target)

0.5188706989510832

In [12]:
confusion_matrix(test_input_target, model.predict(test_input_var).astype(float))

array([[9972, 5666],
       [9058, 5907]])

# p > 1

In [13]:
train_input_var = train.drop(['round_winner', 'map'], axis=1)
train_input_target = train['round_winner'].astype(int)

test_input_var = test.drop(['round_winner', 'map'], axis=1)
test_input_target = test['round_winner'].astype(int)

scaler = StandardScaler()
train_input_var = scaler.fit_transform(train_input_var)
test_input_var = scaler.transform(test_input_var)

In [14]:
model = LogisticRegression()
model = model.fit(train_input_var, train_input_target)

In [19]:
train.columns[np.argmax(model.coef_)]

'bomb_planted'

## Train eval

In [15]:
model.score(train_input_var, train_input_target)

0.7476662999553411

In [16]:
confusion_matrix(train_input_target, model.predict(train_input_var).astype(float))

array([[34583, 12185],
       [10981, 34058]])

## Test eval

In [17]:
model.score(test_input_var, test_input_target)

0.7495997124464922

In [18]:
confusion_matrix(test_input_target, model.predict(test_input_var).astype(float))

array([[11584,  4054],
       [ 3609, 11356]])

In [36]:
from sklearn.feature_selection import SequentialFeatureSelector

In [37]:
train_input_var = train.drop(['round_winner', 'map'], axis=1)
train_input_target = train['round_winner'].astype(int)

test_input_var = test.drop(['round_winner', 'map'], axis=1)
test_input_target = test['round_winner'].astype(int)

scaler = StandardScaler()
train_input_var = scaler.fit_transform(train_input_var)
test_input_var = scaler.transform(test_input_var)

In [38]:
train_input_var.shape

(24482, 95)

In [39]:
model = LogisticRegression()
# model = model.fit(train_input_var, train_input_target)

In [42]:
forward = SequentialFeatureSelector(model, n_features_to_select=20, direction='forward')

In [43]:
forward = forward.fit(train_input_var, train_input_target)

In [56]:
selected = df_cs.drop(['round_winner', 'map'], axis=1).columns[forward.get_support()]
selected

Index(['ct_armor', 't_armor', 't_helmets', 'ct_defuse_kits', 'ct_weapon_aug',
       'ct_weapon_bizon', 't_weapon_elite', 'ct_weapon_g3sg1',
       'ct_weapon_galilar', 'ct_weapon_m249', 't_weapon_m249',
       't_weapon_m4a1s', 'ct_weapon_mag7', 'ct_weapon_mp7', 'ct_weapon_negev',
       't_weapon_negev', 't_weapon_p90', 'ct_weapon_fiveseven',
       'ct_weapon_p250', 't_grenade_flashbang'],
      dtype='object')

In [59]:
train_input_var = train[selected]
train_input_target = train['round_winner'].astype(int)

test_input_var = test[selected]
test_input_target = test['round_winner'].astype(int)

scaler = StandardScaler()
train_input_var = scaler.fit_transform(train_input_var)
test_input_var = scaler.transform(test_input_var)

In [60]:
model = LogisticRegression()
model = model.fit(train_input_var, train_input_target)

In [61]:
model.score(train_input_var, train_input_target)

0.74127930724614

In [62]:
model.score(test_input_var, test_input_target)

0.7366432481006454